### ISSUE TITLE
storage里内容软链接到public之后图片路径有问题

### ISSUE THREAD

**Issue by TyrantG** [dominator88/laravel-smart#2]
![1](https://user-images.githubusercontent.com/31957426/35143267-04f9a214-fd3c-11e7-88c5-668f2a7d66c4.PNG)

![2](https://user-images.githubusercontent.com/31957426/35143865-be71862a-fd3d-11e7-94fa-03f8f92d7dde.PNG)
存到数据库里的图片路径和软链接路径不一致怎么办

**Comment by dominator88** [comment]
使用 asset 函数 或者 使用Storage 的相关门面方法,看能不能获取的正确的图片路径
