### ISSUE TITLE
安装不上呢

### ISSUE THREAD

**Issue by Sdlearn** [dominator88/laravel-smart#4]
提示如下信息：
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/framework[v5.6.17, 5.5.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.6.17].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.6.17].
    - dominator88/laravel-smart dev-master requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - Installation request for dominator88/laravel-smart dev-master -> satisfiable by dominator88/laravel-smart[dev-master].
    - Installation request for laravel/framework (locked at v5.6.17, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.17].

**Comment by dominator88** [comment]
请使用 laravel 5.5
